services:
    web:
        image: ghcr.io/sylius/sylius-php:8.2-fixuid-xdebug-alpine
        environment:
            APP_ENV: "dev"
            DATABASE_URL: "mysql://root:mysql@mysql/sylius_%kernel.environment%?charset=utf8mb4"
#            DATABASE_URL: "pgsql://root:postgres@postgres/sylius_%kernel.environment%?charset=utf8" # When using postgres
            PHP_DATE_TIMEZONE: "Europe/Paris"
        volumes:
            - ./:/srv/sylius:delegated
            - ./.docker/php/php.ini:/etc/php8/php.ini:delegated
            - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf:delegated
        depends_on:
            - mysql
        labels:
            traefik.enable: true
            traefik.http.routers.sylius-file-upload-web.rule: Host(`sylius-file-upload.${USER_SERVERNAME}`)
            traefik.http.routers.sylius-file-upload-web.entrypoints: websecure
    
    mysql:
        image: mysql:8.0
        platform: linux/amd64
        environment:
            MYSQL_ROOT_PASSWORD: mysql

networks:
    default:
        external: true
        name: br-mezcalito
